version: '3'
services:
  fava:
    build: .
    volumes:
      - "./data:/data"
    restart: always
    environment:
      - "BEANCOUNT_INPUT_FILE=/data/tesouraria.beancount"
      - "BEANCOUNT_TITLE=Partido Pirata"
      - "BEANCOUNT_CURRENCY=BRL"
    ports:
      - "42085:5000"
    restart: always
